---

_apt_key:
  - keyring: "/etc/apt/keyrings/docker.gpg"
    url: "https://download.docker.com/linux/ubuntu/gpg"
    #id: "789CFFDE0295B8A1F4E5690C4BECC97550D0B1FD"
    state: "present"

_apt_repository:
  - filename: "docker"
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu focal stable"
    state: "present"

_apt:
  - { state: "latest", name: "ca-certificates" }
  - { state: "latest", name: "curl" }
  - { state: "latest", name: "lsb-release" }
  - { state: "latest", name: "gnupg" }
  - { state: "latest", name: "docker-ce" }
  - { state: "latest", name: "docker-ce-cli" }
  - { state: "latest", name: "containerd.io" }
  - { state: "latest", name: "docker-compose-plugin" }
  - { state: "latest", name: "docker-ce-rootless-extras" }
  - { state: "latest", name: "docker-compose" }