---
# handlers file for kali-common

- name: bootstrap | systemctl restart systemd-sysctl.service
  ansible.builtin.service:
    name: "systemd-sysctl.service"
    state: "restarted"
  changed_when: false
  failed_when: false